### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by alwaystest** [eycorsican/go-tun2socks-mobile#13]
按照 Readme 的指导去编译 Android  的 AAR 出来，报错。查看 Trace 发现错误的地方如下：

https://github.com/eycorsican/go-tun2socks-mobile/blob/master/tun2socks.go#L23

应该是 go-tun2socks 主分支代码更新了，这里在下载依赖的时候没有锁定当时可以编译通过的版本，而是下载了 go-tun2socks 的主分支的代码，导致无法编译。

另外 kitsunebi-android 项目的代码后面不会再开源了吗？我看 Github 上的版本只更新到 0.9.2， Play 上发布的已经到 1.6.12 了。

**Comment by Shameless521** [comment]
ios fail: not enough arguments in call to socks.NewTCPHandler
