### ISSUE TITLE
IOS如何集成 PacketFlow 这个参数如何传？

### ISSUE THREAD

**Issue by iworkcloud** [eycorsican/go-tun2socks-mobile#28]
IOS如何集成 func StartSocks(packetFlow PacketFlow, proxyHost string, proxyPort int)  PacketFlow这个参数如何传？

![image](https://user-images.githubusercontent.com/2082094/110910794-c7563180-834c-11eb-9996-6bf0d80087da.png)

run_leaf 不需要PacketFlow这个参数

**Comment by eycorsican** [comment]
有rust 写的 leaf还有什么理由用Go的？

**Comment by iworkcloud** [comment]
我们写了自定义协议的framework，也是基于这个库。

**Comment by eycorsican** [comment]
别在iOS上用这个

**Comment by iworkcloud** [comment]
会超出15M内存占用吗？

**Comment by eycorsican** [comment]
Outline就是用这个，他们只是运行简单的SS协议，大部分情况还不会超，具体你可以过去问问。如果你的协议涉及到TLS的话随时会超内存。

**Comment by iworkcloud** [comment]
好的，谢谢您的回复，我再研究研究！
